# Generated by Django 2.1.5 on 2019-03-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_dob', models.CharField(max_length=10)),
                ('admin_gender', models.CharField(max_length=8)),
                ('admin_mobile', models.PositiveIntegerField()),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_pwd', models.TextField()),
                ('school_name', models.TextField()),
                ('school_address', models.TextField()),
                ('school_mobile', models.PositiveIntegerField()),
                ('clerk_name', models.CharField(max_length=100)),
                ('clerk_id', models.TextField()),
                ('clerk_pwd', models.TextField()),
                ('dashboard_id', models.TextField()),
                ('dashboard_pwd', models.TextField()),
            ],
        ),
    ]
