# Generated by Django 2.1.5 on 2019-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=101)),
                ('admin_dob', models.CharField(max_length=10)),
                ('admin_gender', models.CharField(max_length=8)),
                ('admin_mobile', models.PositiveIntegerField()),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_pwd', models.TextField()),
                ('school_name', models.TextField()),
                ('school_address', models.TextField()),
                ('school_mobile', models.PositiveIntegerField()),
                ('clerk_name', models.CharField(max_length=100)),
                ('clerk_id', models.TextField()),
                ('clerk_pwd', models.TextField()),
                ('dashboard_id', models.TextField()),
                ('dashboard_pwd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='attendance_faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=10)),
                ('Enroll', models.PositiveIntegerField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='attendance_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=10)),
                ('std', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='declarationtoall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('declared_on', models.CharField(max_length=10)),
                ('event_date', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='declarationtosp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('declared_on', models.CharField(max_length=10)),
                ('event_date', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('people_type', models.CharField(max_length=12)),
                ('Enroll', models.PositiveIntegerField()),
                ('std', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=75)),
                ('dob', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feesrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('std', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('paidfees', models.PositiveIntegerField()),
                ('year', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('std', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=75)),
                ('father_name', models.CharField(max_length=75)),
                ('father_occupation', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='totalfees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('s1', models.PositiveIntegerField()),
                ('s2', models.PositiveIntegerField()),
                ('s3', models.PositiveIntegerField()),
                ('s4', models.PositiveIntegerField()),
                ('s5', models.PositiveIntegerField()),
                ('s6', models.PositiveIntegerField()),
                ('s7', models.PositiveIntegerField()),
                ('s8', models.PositiveIntegerField()),
                ('s9', models.PositiveIntegerField()),
                ('s10', models.PositiveIntegerField()),
                ('s11', models.PositiveIntegerField()),
                ('s12', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('isfeesset', models.BooleanField(default=False)),
            ],
        ),
    ]
