# Generated by Django 2.1.5 on 2019-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='admin_name',
            field=models.CharField(max_length=101),
        ),
    ]
