# Generated by Django 2.1.5 on 2019-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190329_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('std', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=75)),
                ('father_name', models.CharField(max_length=75)),
                ('father_occupation', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
