# Generated by Django 3.1.5 on 2021-01-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201225_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='school_mobile',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='school_name',
        ),
    ]
