# Generated by Django 2.1.5 on 2019-04-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_details',
        ),
    ]
