# Generated by Django 2.1.5 on 2019-04-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_student_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=75)),
                ('dob', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
