# Generated by Django 2.1.5 on 2019-04-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_faculty_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='attendance_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('std', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
