# Generated by Django 2.1.5 on 2019-04-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_attendance_faculty_attendance_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance_faculty',
        ),
        migrations.DeleteModel(
            name='attendance_student',
        ),
    ]
