# Generated by Django 2.1.5 on 2019-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_attendance_faculty_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalfees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('s1', models.PositiveIntegerField()),
                ('s2', models.PositiveIntegerField()),
                ('s3', models.PositiveIntegerField()),
                ('s4', models.PositiveIntegerField()),
                ('s5', models.PositiveIntegerField()),
                ('s6', models.PositiveIntegerField()),
                ('s7', models.PositiveIntegerField()),
                ('s8', models.PositiveIntegerField()),
                ('s9', models.PositiveIntegerField()),
                ('s10', models.PositiveIntegerField()),
                ('s11', models.PositiveIntegerField()),
                ('s12', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('isfeesset', models.BooleanField(default=False)),
            ],
        ),
    ]
