# Generated by Django 2.1.5 on 2019-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_totalfees_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='feesrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.PositiveIntegerField()),
                ('Enroll', models.PositiveIntegerField()),
                ('paidfees', models.PositiveIntegerField()),
                ('year', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
