# Generated by Django 2.1.5 on 2019-04-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_feesrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feesrecord',
        ),
    ]
