# Generated by Django 2.1.5 on 2019-04-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_declarationtoall_declarationtosp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='declarationtoall',
        ),
        migrations.DeleteModel(
            name='declarationtosp',
        ),
    ]
